[package]
name = "hyper-timeout"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]
futures = "0.1.11"
hyper = "0.11.0"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-service = "0.1.0"

[dev-dependencies]
native-tls = "0.1"
hyper-tls = "0.1.1"
