[package]
name = "hyper-timeout"
version = "0.1.2"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[badges]
travis-ci = { repository = "https://github.com/hjr3/hyper-timeout", branch = "master" }

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-service = "0.1"
tokio-io-timeout = "0.3"

[dev-dependencies]
native-tls = "0.1"
hyper-tls = "0.1"
